// <auto-generated />
namespace Employement_Project_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class newdatatypephone2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newdatatypephone2));
        
        string IMigrationMetadata.Id
        {
            get { return "202301302013526_newdatatypephone2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
